name: uaa

services:
  postgres:
    image: "postgres:17.2"
    ports:
      - 5432:5432
    volumes:
      - ./scripts/postgresql:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=changeme

  mysql:
    image: "mysql:8"
    ports:
      - 3306:3306
    volumes:
      - ./scripts/mysql:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=changeme