name: uaa

services:
  postgres:
    image: "postgres:15"
    ports:
      - 5432:5432
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d/
      - type: tmpfs
        target: /var/lib/postgresql/data
        tmpfs:
          size: 1073741824 # 1024 * 2^20 bytes = 1024Mb
    environment:
      - POSTGRES_PASSWORD=changeme
    command:
      - postgres
      - -c
      - max_connections=1000
  mysql:
    image: "mysql:8"
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/
      - /etc/localtime:/localtime-from-host
      - type: tmpfs
        target: /var/lib/mysql
        tmpfs:
          size: 1073741824 # 1024 * 2^20 bytes = 1024Mb
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - TZ=${TZ}
    command:
      - --sql_mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION,PAD_CHAR_TO_FULL_LENGTH
  openldap:
    image: docker.io/bitnami/openldap:2.6
    ports:
      - '389:1389'
      - '636:1636'
    # docs of these env vars: https://github.com/bitnami/containers/tree/2724f9cd02b3b4e7986a1e2a0b0b30af3737bbd2/bitnami/openldap#configuration
    environment:
      - LDAP_ROOT=dc=test,dc=com
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=password
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
      - LDAP_GROUP=some-ldap-group
    volumes:
      - 'openldap_data:/bitnami/openldap'

volumes:
  openldap_data:
    driver: local